services:
    _defaults:
        public: true

    sfes.document_converter: '@Sineflow\ElasticsearchBundle\Result\DocumentConverter'
    sfes.provider_registry: '@Sineflow\ElasticsearchBundle\Document\Provider\ProviderRegistry'
    sfes.index_manager_factory: '@Sineflow\ElasticsearchBundle\Manager\IndexManagerFactory'
    sfes.index_manager_registry: '@Sineflow\ElasticsearchBundle\Manager\IndexManagerRegistry'
    sfes.finder: '@Sineflow\ElasticsearchBundle\Finder\Finder'
    sfes.document_locator: '@Sineflow\ElasticsearchBundle\Mapping\DocumentLocator'
    sfes.document_parser: '@Sineflow\ElasticsearchBundle\Mapping\DocumentParser'
    sfes.document_metadata_collector: '@Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector'
    sfes.logger.collection_handler: '@Sineflow\ElasticsearchBundle\Profiler\Handler\CollectionHandler'
    sfes.connection_factory: '@Sineflow\ElasticsearchBundle\Manager\ConnectionManagerFactory'
    sfes.profiler: '@Sineflow\ElasticsearchBundle\Profiler\ElasticsearchProfiler'
    sfes.subscriber.knp_paginate_query_subscriber: '@Sineflow\ElasticsearchBundle\Subscriber\KnpPaginateQuerySubscriber'
    sfes.subscriber.entity_tracker_subscriber: '@Sineflow\ElasticsearchBundle\Subscriber\EntityTrackerSubscriber'
