imports:
    - { resource: services_commands.yml }

parameters:
    sfes.logging.path: "%kernel.logs_dir%/%kernel.environment%.sf_elasticsearch.log"
    sfes.profiler_backtrace_enabled: false
    sfes.mlproperty.language_separator: '-'

    sfes.provider_self.class: Sineflow\ElasticsearchBundle\Document\Provider\ElasticsearchProvider

services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: false
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: false
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    sfes.connection_manager_prototype:
        abstract: true
        class: Sineflow\ElasticsearchBundle\Manager\ConnectionManager
        arguments:
            - # connection name
            - # connection settings

    sfes.index_manager_prototype:
        abstract: true
        class: Sineflow\ElasticsearchBundle\Manager\IndexManager
        arguments:
            - # manager name
            - # index settings
            - # connection
            - '@Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector'
            - '@Sineflow\ElasticsearchBundle\Document\Provider\ProviderRegistry'
            - '@Sineflow\ElasticsearchBundle\Finder\Finder'
            - '@Sineflow\ElasticsearchBundle\Result\DocumentConverter'
            - '@Sineflow\ElasticsearchBundle\Document\Repository\RepositoryFactory'

    Sineflow\ElasticsearchBundle\Manager\IndexManagerRegistry:
        arguments:
            - '@Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector'
            - !tagged_locator { tag: 'sfes.index_manager' }

    Sineflow\ElasticsearchBundle\Result\DocumentConverter:
        arguments:
            - '@Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector'
            - '%sfes.mlproperty.language_separator%'

    Sineflow\ElasticsearchBundle\Document\Repository\RepositoryFactory:
        arguments:
            - !tagged_locator { tag: 'sfes.repository' }
            - '@Sineflow\ElasticsearchBundle\Finder\Finder'

    Sineflow\ElasticsearchBundle\Document\Provider\ProviderRegistry:
        arguments:
            - !tagged_locator { tag: 'sfes.provider' }
            - '@Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector'
            - '@Sineflow\ElasticsearchBundle\Manager\IndexManagerRegistry'
            - '%sfes.provider_self.class%'

    Sineflow\ElasticsearchBundle\Finder\Finder:
        arguments:
            - '@Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector'
            - '@Sineflow\ElasticsearchBundle\Manager\IndexManagerRegistry'
            - '@Sineflow\ElasticsearchBundle\Result\DocumentConverter'

    Sineflow\ElasticsearchBundle\Mapping\DocumentLocator:
        arguments:
            - '%sfes.entity_locations%'

    Sineflow\ElasticsearchBundle\Mapping\DocumentParser:
        arguments:
            - '@sfes.annotations.cached_reader'
            - '@Sineflow\ElasticsearchBundle\Mapping\DocumentLocator'
            - '%sfes.mlproperty.language_separator%'
            - '%sfes.languages%'

    Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector:
        arguments:
            - '%sfes.indices%'
            - '@Sineflow\ElasticsearchBundle\Mapping\DocumentLocator'
            - '@Sineflow\ElasticsearchBundle\Mapping\DocumentParser'
            - '@sfes.cache_engine'
            - '%kernel.debug%'

    Sineflow\ElasticsearchBundle\Profiler\Handler\CollectionHandler:
        arguments:
            - '@request_stack'
            - '%sfes.profiler_backtrace_enabled%'

    Sineflow\ElasticsearchBundle\Profiler\ElasticsearchProfiler:
        calls:
            - [setIndexManagers, ['%sfes.indices%']]
            - [addLogger, ['@sfes.logger.trace']]
        tags:
            - {name: data_collector, template: '@SineflowElasticsearch/Profiler/profiler.html.twig', id: sfes.profiler}

    Sineflow\ElasticsearchBundle\Subscriber\KnpPaginateQuerySubscriber:
        arguments: ['@request_stack']
        tags:
            - { name: knp_paginator.subscriber }

    Sineflow\ElasticsearchBundle\Subscriber\EntityTrackerSubscriber:
        arguments:
            - '@Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector'
        tags:
            - { name: kernel.event_subscriber }

    sfes.cache_engine:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ['%kernel.cache_dir%/sineflow', '.sineflow.data']
        public: true

    sfes.annotations.cached_reader:
        class: Doctrine\Common\Annotations\CachedReader
        arguments:
            - '@annotations.reader'
            - '@sfes.cache_engine'
            - '%kernel.debug%'

    sfes.logger.trace:
        class: Monolog\Logger
        arguments: ['sfes_trace']
        calls:
            - [pushHandler, ['@Sineflow\ElasticsearchBundle\Profiler\Handler\CollectionHandler']]

    sfes.logger.log_handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments: ['%sfes.logging.path%', 0, notice]

    sfes.logger.log:
        class: Monolog\Logger
        arguments: ['sfes_log']
        calls:
            - [pushHandler, ['@sfes.logger.log_handler']]
