parameters:
    sfes.logging.path: "%kernel.logs_dir%/%kernel.environment%.sf_elasticsearch.log"
    sfes.profiler_backtrace_enabled: false
    sfes.profiler.template: SineflowElasticsearchBundle:Profiler:profiler.html.twig
    sfes.mlproperty.language_separator: '-'

    sfes.provider_self.class: Sineflow\ElasticsearchBundle\Document\Provider\ElasticsearchProvider
    sfes.index_manager.class: Sineflow\ElasticsearchBundle\Manager\IndexManager

services:
    sfes.document_converter:
        class: Sineflow\ElasticsearchBundle\Result\DocumentConverter
        arguments: ['@sfes.document_metadata_collector', '%sfes.mlproperty.language_separator%']

    sfes.provider_registry:
        class: Sineflow\ElasticsearchBundle\Document\Provider\ProviderRegistry
        calls:
            - [setContainer, ['@service_container']]

    sfes.index_manager_factory:
        class: Sineflow\ElasticsearchBundle\Manager\IndexManagerFactory
        arguments:
            - '@sfes.document_metadata_collector'
            - '@sfes.provider_registry'
            - '@sfes.finder'
            - '@sfes.document_converter'
            - '%sfes.mlproperty.language_separator%'
        calls:
            - [setEventDispatcher, ['@event_dispatcher']]
        public: false

    sfes.index_manager_registry:
        class: Sineflow\ElasticsearchBundle\Manager\IndexManagerRegistry
        arguments: ['@sfes.document_metadata_collector']
        calls:
            - [setContainer, ['@service_container']]

    sfes.finder:
        class: Sineflow\ElasticsearchBundle\Finder\Finder
        arguments: ['@sfes.document_metadata_collector', '@sfes.index_manager_registry', '@sfes.document_converter']

    sfes.document_locator:
        class: Sineflow\ElasticsearchBundle\Mapping\DocumentLocator
        arguments: ['%kernel.bundles%']
        calls:
            - [setDocumentDir, ['%sfes.document_dir%']]

    sfes.cache_engine:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ['%kernel.cache_dir%/sineflow', '.sineflow.data']
        public: false

    sfes.annotations.reader:
        class: Doctrine\Common\Annotations\AnnotationReader
        public: false

    sfes.annotations.cached_reader:
        class: Doctrine\Common\Annotations\CachedReader
        arguments: ['@sfes.annotations.reader', '@sfes.cache_engine', '%kernel.debug%']
        public: false

    sfes.document_parser:
        class: Sineflow\ElasticsearchBundle\Mapping\DocumentParser
        arguments: ['@sfes.annotations.cached_reader', '@sfes.document_locator', '%sfes.mlproperty.language_separator%']

    sfes.document_metadata_collector:
        class: Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector
        arguments: ['%sfes.indices%', '@sfes.document_locator', '@sfes.document_parser', '@sfes.cache_engine', '%kernel.debug%']

    sfes.logger.collection_handler:
        class: Sineflow\ElasticsearchBundle\Profiler\Handler\CollectionHandler
        arguments: ['@request_stack', '%sfes.profiler_backtrace_enabled%']
        public: false

    sfes.logger.trace:
        class: Monolog\Logger
        arguments: ['sfes_trace']
        calls:
            - [pushHandler, ['@sfes.logger.collection_handler']]

    sfes.logger.log_handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments: ['%sfes.logging.path%', 0, notice]

    sfes.logger.log:
        class: Monolog\Logger
        arguments: ['sfes_log']
        calls:
            - [pushHandler, ['@sfes.logger.log_handler']]

    sfes.connection_factory:
        class: Sineflow\ElasticsearchBundle\Manager\ConnectionManagerFactory
        arguments: ['%kernel.debug%', '@sfes.logger.trace', '@sfes.logger.log']
        calls:
            - [setEventDispatcher, ['@event_dispatcher']]

    sfes.profiler:
        class: Sineflow\ElasticsearchBundle\Profiler\ElasticsearchProfiler
        calls:
            - [setIndexManagers, ['%sfes.indices%']]
            - [addLogger, ['@sfes.logger.trace']]
        tags:
            - {name: data_collector, template: '%sfes.profiler.template%', id: sfes.profiler}

    sfes.subscriber.knp_paginate_query_subscriber:
        class: Sineflow\ElasticsearchBundle\Subscriber\KnpPaginateQuerySubscriber
        arguments: ['@request_stack']
        tags:
            - { name: knp_paginator.subscriber }

    sfes.subscriber.entity_tracker_subscriber:
        class: Sineflow\ElasticsearchBundle\Subscriber\EntityTrackerSubscriber
        arguments: ['@sfes.document_metadata_collector']
        tags:
            - { name: kernel.event_subscriber }
