parameters:
    sfes.logging.path: "%kernel.logs_dir%/%kernel.environment%.sf_elasticsearch.log"
    sfes.profiler_backtrace_enabled: false
    sfes.profiler.template: SineflowElasticsearchBundle:Profiler:profiler.html.twig
    sfes.mlproperty.language_separator: '-'

    sfes.provider_registry.class: Sineflow\ElasticsearchBundle\Document\Provider\ProviderRegistry
    sfes.provider_self.class: Sineflow\ElasticsearchBundle\Document\Provider\ElasticsearchProvider
    sfes.index_manager.class: Sineflow\ElasticsearchBundle\Manager\IndexManager
    sfes.index_manager_factory.class: Sineflow\ElasticsearchBundle\Manager\IndexManagerFactory
    sfes.index_manager_registry.class: Sineflow\ElasticsearchBundle\Manager\IndexManagerRegistry
    sfes.finder.class: Sineflow\ElasticsearchBundle\Finder\Finder
    sfes.document_locator.class: Sineflow\ElasticsearchBundle\Mapping\DocumentLocator
    sfes.document_parser.class: Sineflow\ElasticsearchBundle\Mapping\DocumentParser
    sfes.document_metadata_collector.class: Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector
    sfes.logger.collection_handler.class: Sineflow\ElasticsearchBundle\Profiler\Handler\CollectionHandler
    sfes.connection_factory.class: Sineflow\ElasticsearchBundle\Manager\ConnectionManagerFactory
    sfes.profiler.class: Sineflow\ElasticsearchBundle\Profiler\ElasticsearchProfiler
    sfes.knp_paginate_query_subscriber_class: Sineflow\ElasticsearchBundle\Subscriber\KnpPaginateQuerySubscriber

services:
    sfes.provider_registry:
        class: %sfes.provider_registry.class%
        calls:
            - [setContainer, ["@service_container"]]

    sfes.index_manager_factory:
        class: %sfes.index_manager_factory.class%
        arguments: [@sfes.document_metadata_collector, @sfes.provider_registry, @sfes.finder, %sfes.mlproperty.language_separator%]
        public: false

    sfes.index_manager_registry:
        class: %sfes.index_manager_registry.class%
        calls:
            - [setContainer, ["@service_container"]]

    sfes.finder:
        class: %sfes.finder.class%
        arguments: [@sfes.document_metadata_collector, @sfes.index_manager_registry, %sfes.mlproperty.language_separator%]

    sfes.document_locator:
        class: %sfes.document_locator.class%
        arguments: [%kernel.bundles%]
        calls:
            - [setDocumentDir, ["%sfes.document_dir%"]]

    sfes.cache_engine:
        class: %doctrine_cache.file_system.class%
        arguments: ["%kernel.cache_dir%/sineflow", ".sineflow.data"]
        public: false

    sfes.annotations.reader:
        class: %annotations.reader.class%
        public: false

    sfes.annotations.cached_reader:
        class: %annotations.cached_reader.class%
        arguments: [@sfes.annotations.reader, @sfes.cache_engine, %kernel.debug%]
        public: false

    sfes.document_parser:
        class: %sfes.document_parser.class%
        arguments: [@sfes.annotations.cached_reader, @sfes.document_locator, %sfes.mlproperty.language_separator%]
        public: false

    sfes.document_metadata_collector:
        class: %sfes.document_metadata_collector.class%
        arguments: [%sfes.indices%, @sfes.document_locator, @sfes.document_parser, @sfes.cache_engine, %kernel.debug%]

    sfes.logger.collection_handler:
        class: %sfes.logger.collection_handler.class%
        arguments: [@request_stack, %sfes.profiler_backtrace_enabled%]
        public: false

    sfes.logger.trace:
        class: %monolog.logger.class%
        arguments: ['sfes_trace']
        calls:
            - [pushHandler, [@sfes.logger.collection_handler]]

    sfes.logger.log_handler:
        class: %monolog.handler.rotating_file.class%
        arguments: [%sfes.logging.path%, 0, notice]

    sfes.logger.log:
        class: %monolog.logger.class%
        arguments: ['sfes_log']
        calls:
            - [pushHandler, [@sfes.logger.log_handler]]

    sfes.connection_factory:
        class: %sfes.connection_factory.class%
        arguments: [%kernel.debug%, @sfes.logger.trace, @sfes.logger.log]

    sfes.profiler:
        class: %sfes.profiler.class%
        calls:
            - [setIndexManagers, [%sfes.indices%]]
            - [addLogger, [@sfes.logger.trace]]
        tags:
            - {name: data_collector, template: %sfes.profiler.template%, id: sfes.profiler}

    sfes.subscriber.knp_paginate_query_subscriber:
        class: %sfes.knp_paginate_query_subscriber_class%
        arguments: [@request_stack]
        tags:
            - { name: knp_paginator.subscriber }
