parameters:
    sfes.provider_registry.class: Sineflow\ElasticsearchBundle\Document\Provider\ProviderRegistry
    sfes.index_manager_factory.class: Sineflow\ElasticsearchBundle\Manager\IndexManagerFactory
    sfes.finder.class: Sineflow\ElasticsearchBundle\Finder\Finder
#    sfes.logging.path: %kernel.logs_dir%/elasticsearch_%kernel.environment%.log
#    sfes.export.class: ONGR\ElasticsearchBundle\Service\ExportService
#    sfes.import.class: ONGR\ElasticsearchBundle\Service\ImportService
    sfes.document_locator.class: Sineflow\ElasticsearchBundle\Mapping\DocumentLocator
    sfes.document_parser.class: Sineflow\ElasticsearchBundle\Mapping\DocumentParser
    sfes.document_metadata_collector.class: Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector
    sfes.logger.collection_handler.class: Sineflow\ElasticsearchBundle\Profiler\Handler\CollectionHandler
    sfes.profiler.class: Sineflow\ElasticsearchBundle\Profiler\ElasticsearchProfiler
    sfes.profiler.template: SineflowElasticsearchBundle:Profiler:profiler.html.twig

services:
#    sfes.export:
#        class: %sfes.export.class%
#
#    sfes.import:
#        class: %sfes.import.class%

    sfes.provider_registry:
        class: %sfes.provider_registry.class%
        calls:
            - [setContainer, ["@service_container"]]

    sfes.index_manager_factory:
        class: %sfes.index_manager_factory.class%
        calls:
            - [setContainer, ["@service_container"]]

    sfes.finder:
        class: %sfes.finder.class%
        arguments: [@sfes.document_metadata_collection, @sfes.index_manager_factory]

    sfes.document_locator:
        class: %sfes.document_locator.class%
        arguments: [%kernel.bundles%]
        calls:
            - [setDocumentDir, ["%sfes.document_dir%"]]

    sfes.cache_engine:
        class: %doctrine_cache.file_system.class%
        arguments: ["%kernel.cache_dir%/sineflow", ".sineflow.data"]
        public: false

    sfes.annotations.reader:
        class: %annotations.reader.class%
        public: false

    sfes.annotations.cached_reader:
        class: %annotations.cached_reader.class%
        arguments: [@sfes.annotations.reader, @sfes.cache_engine, %kernel.debug%]
        public: false

    sfes.document_parser:
        class: %sfes.document_parser.class%
        arguments: [@sfes.annotations.cached_reader, @sfes.document_locator]
        public: false

    sfes.document_metadata_collector:
        class: %sfes.document_metadata_collector.class%
        arguments: [@sfes.document_locator, @sfes.document_parser]

    sfes.logger.collection_handler:
        class: %sfes.logger.collection_handler.class%
        arguments: [@request_stack]
        public: false

    sfes.logger.trace:
        class: %monolog.logger.class%
        arguments: ['trace']
        calls:
            - [pushHandler, [@sfes.logger.collection_handler]]

    sfes.profiler:
        class: %sfes.profiler.class%
        calls:
            - [setIndexManagers, [%sfes.indices%]]
            - [addLogger, [@sfes.logger.trace]]
        tags:
            - {name: data_collector, template: %sfes.profiler.template%, id: sfes}
