imports:
    - { resource: legacy_aliases.yml }

parameters:
    sfes.logging.path: "%kernel.logs_dir%/%kernel.environment%.sf_elasticsearch.log"
    sfes.profiler_backtrace_enabled: false
    sfes.mlproperty.language_separator: '-'

    sfes.provider_self.class: Sineflow\ElasticsearchBundle\Document\Provider\ElasticsearchProvider
    sfes.index_manager.class: Sineflow\ElasticsearchBundle\Manager\IndexManager

services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: false
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: false
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Sineflow\ElasticsearchBundle\Result\DocumentConverter:
        arguments: ['@sfes.document_metadata_collector', '%sfes.mlproperty.language_separator%']

    Sineflow\ElasticsearchBundle\Document\Provider\ProviderRegistry:
        arguments:
            - '@sfes.document_metadata_collector'
            - '@sfes.index_manager_registry'
            - '%sfes.provider_self.class%'
        calls:
            - [ setContainer, [ '@service_container' ]]

    Sineflow\ElasticsearchBundle\Manager\IndexManagerFactory:
        arguments:
            - '@sfes.document_metadata_collector'
            - '@sfes.provider_registry'
            - '@sfes.finder'
            - '@sfes.document_converter'
            - '%sfes.mlproperty.language_separator%'
        calls:
            - [setEventDispatcher, ['@event_dispatcher']]
        public: false

    Sineflow\ElasticsearchBundle\Manager\IndexManagerRegistry:
        arguments: ['@sfes.document_metadata_collector']
        calls:
            - [setContainer, ['@service_container']]

    Sineflow\ElasticsearchBundle\Finder\Finder:
        arguments: ['@sfes.document_metadata_collector', '@sfes.index_manager_registry', '@sfes.document_converter']

    Sineflow\ElasticsearchBundle\Mapping\DocumentLocator:
        arguments: ['%kernel.bundles%']
        calls:
            - [setDocumentDir, ['%sfes.document_dir%']]

    Sineflow\ElasticsearchBundle\Mapping\DocumentParser:
        arguments: ['@sfes.annotations.cached_reader', '@sfes.document_locator', '%sfes.mlproperty.language_separator%']

    Sineflow\ElasticsearchBundle\Mapping\DocumentMetadataCollector:
        arguments: ['%sfes.indices%', '@sfes.document_locator', '@sfes.document_parser', '@sfes.cache_engine', '%kernel.debug%']

    Sineflow\ElasticsearchBundle\Profiler\Handler\CollectionHandler:
        arguments: ['@request_stack', '%sfes.profiler_backtrace_enabled%']
        public: false

    Sineflow\ElasticsearchBundle\Manager\ConnectionManagerFactory:
        arguments: ['%kernel.debug%', '@sfes.logger.trace', '@sfes.logger.log']
        calls:
            - [setEventDispatcher, ['@event_dispatcher']]

    Sineflow\ElasticsearchBundle\Profiler\ElasticsearchProfiler:
        calls:
            - [setIndexManagers, ['%sfes.indices%']]
            - [addLogger, ['@sfes.logger.trace']]
        tags:
            - {name: data_collector, template: "@SineflowElasticsearch/Profiler/profiler.html.twig", id: sfes.profiler}

    Sineflow\ElasticsearchBundle\Subscriber\KnpPaginateQuerySubscriber:
        arguments: ['@request_stack']
        tags:
            - { name: knp_paginator.subscriber }

    Sineflow\ElasticsearchBundle\Subscriber\EntityTrackerSubscriber:
        arguments: ['@sfes.document_metadata_collector']
        tags:
            - { name: kernel.event_subscriber }

    sfes.cache_engine:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ['%kernel.cache_dir%/sineflow', '.sineflow.data']
        public: true

    sfes.annotations.reader:
        class: Doctrine\Common\Annotations\AnnotationReader
        public: false

    sfes.annotations.cached_reader:
        class: Doctrine\Common\Annotations\CachedReader
        arguments: ['@sfes.annotations.reader', '@sfes.cache_engine', '%kernel.debug%']
        public: false

    sfes.logger.trace:
        class: Monolog\Logger
        arguments: ['sfes_trace']
        calls:
            - [pushHandler, ['@sfes.logger.collection_handler']]

    sfes.logger.log_handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments: ['%sfes.logging.path%', 0, notice]

    sfes.logger.log:
        class: Monolog\Logger
        arguments: ['sfes_log']
        calls:
            - [pushHandler, ['@sfes.logger.log_handler']]
