language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  global:
    - SYMFONY_VERSION="~3.4" ES_FILENAME_SUFFIX=""
  matrix:
    - ES_VERSION="6.2.0"
    - ES_VERSION="6.8.1"
    - ES_VERSION="6.8.1" SYMFONY_VERSION="~4.0"
#    - ES_VERSION="7.2.0" SYMFONY_VERSION="~4.0" ES_FILENAME_SUFFIX="-linux-x86_64"

install:
  - composer require --no-update symfony/symfony:${SYMFONY_VERSION}
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}${ES_FILENAME_SUFFIX}.tar.gz
  - tar -xzf elasticsearch-${ES_VERSION}${ES_FILENAME_SUFFIX}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch > /dev/null 2>&1 &
  - composer install --dev --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=Tests/App/build/clover.xml
  - vendor/bin/phpcs -np --standard=PSR2 --ignore=vendor/,Tests/App/ ./

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
