language: php
php:
  - '7.1'
  - '7.3'

env:
  - SYMFONY_VERSION="3.4.*" ES_VERSION="6.2.4"

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 7.1
      env: SYMFONY_VERSION="3.4.*" ES_VERSION="6.8.1"
    - php: 7.1
      env: SYMFONY_VERSION="3.4.*" ES_VERSION="7.2.0"
    - php: 7.1
      env: SYMFONY_VERSION="3.0.*" ES_VERSION="6.2.4"
    - php: 7.1
      env: SYMFONY_VERSION="2.7.*" ES_VERSION="6.2.4"

install:
  - composer require --no-update symfony/symfony:${SYMFONY_VERSION}
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch > /dev/null 2>&1 &
  - composer install --dev --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=Tests/app/build/clover.xml
  - vendor/bin/phpcs -np --standard=PSR2 --ignore=vendor/,Tests/app/ ./

after_script:
  - travis_retry php vendor/bin/coveralls
